name: unicorn-binance-local-depth-cache

channels:
  - lucit
  - conda-forge
  - defaults

dependencies:
  - python>=3.8
  - aiohttp
  - lucit::unicorn-binance-rest-api>=2.8.1
  - lucit::unicorn-binance-websocket-api>=2.10.2
  - cython>=3.0.10
  - requests>=2.31.0
